# Generated by Django 3.2 on 2021-09-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210919_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
