# Generated by Django 3.2 on 2021-09-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='tag',
            new_name='tags',
        ),
    ]
